import type {Metadata} from 'next';
import './globals.css';

import { Geist, Geist_Mono } from 'next/font/google';

import { Button } from '@/components/ui/button';
import {
	ClerkProvider,
	Show,
	SignInButton,
	SignUpButton,
	UserButton,
} from '@clerk/nextjs';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}
        >
            <body className='min-h-full flex flex-col bg-slate-950 text-slate-50'>
                <ClerkProvider
                    signInFallbackRedirectUrl='/dashboard'
                    signUpFallbackRedirectUrl='/dashboard'
                >
                    <header className='border-b border-slate-800 px-6 py-4 mb-6'>
                        <div className='flex items-center justify-between'>
                            <h1 className='text-2xl font-bold'>
                                Link Shortner
                            </h1>
                            <div className='flex items-center gap-4'>
                                <Show when='signed-out'>
                                    <SignInButton mode='modal'>
                                        <Button variant='default'>
                                            Sign in
                                        </Button>
                                    </SignInButton>
                                    <SignUpButton mode='modal'>
                                        <Button variant='outline'>
                                            Sign up
                                        </Button>
                                    </SignUpButton>
                                </Show>
                                <Show when='signed-in'>
                                    <UserButton />
                                </Show>
                            </div>
                        </div>
                    </header>
                    {children}
                </ClerkProvider>
            </body>
        </html>
    );
}
